

CREATE TABLE MENU(
	FOOD_NAME VARCHAR2(20),
	FOOD_FOOD VARCHAR2(20),
	SALARY NUMBER
);


INSERT INTO MENU VALUES ('기본김밥','김밥',3000);
INSERT INTO MENU VALUES ('참치김밥','김밥',4000);
INSERT INTO MENU VALUES ('우엉김밥','김밥',4000);
INSERT INTO MENU VALUES ('돈까스김밥','김밥',5000);
INSERT INTO MENU VALUES ('기본라면','라면',4000);
INSERT INTO MENU VALUES ('하얀라면','라면',5000);
INSERT INTO MENU VALUES ('돈까스','돈까스',8000);
INSERT INTO MENU VALUES ('등심돈까스','돈까스',9000);
INSERT INTO MENU VALUES ('볶음밥','볶음밥',7000);
INSERT INTO MENU VALUES ('새우볶음밥','볶음밥',8000);


SELECT *FROM MENU;


